# 6.1 Data sourcing and Cleaning
## The script contains the following

### Importing librairies, defining the path and importing datastes

### Exploration of the datasets
####   Dataset 2015
####   Dataset 2016
####   Dataset 2017
####   Dataset 2018
####   Dataset 2019

### Renaming columns in each datasets

### Changing datatypes for years and happiness rank

### Deleting columns region for 2015 and 2016

### Descriptive analysis

### Finding missing values

### Checking for duplicates

### Merging all the datasets based on the country variable

### Exporting the dataset

# Importing libraries, defining the path and importing datasets

In [536]:
# Import librairies
import pandas as pd
import numpy as np
import os

In [538]:
# Defiuning the path
path = r'C:\Users\salmi\Desktop\achievement 6'

In [540]:
# Importing the datasets

df_2015 = pd.read_csv(os.path.join(path, 'Data sets', 'Original Data Happiness', '2015.csv'), index_col = False)
df_2016 = pd.read_csv(os.path.join(path, 'Data sets', 'Original Data Happiness', '2016.csv'), index_col = False)
df_2017 = pd.read_csv(os.path.join(path, 'Data sets', 'Original Data Happiness', '2017.csv'), index_col = False)
df_2018 = pd.read_csv(os.path.join(path, 'Data sets', 'Original Data Happiness', '2018.csv'), index_col = False)
df_2019 = pd.read_csv(os.path.join(path, 'Data sets', 'Original Data Happiness', '2019.csv'), index_col = False)

## Exploration of the datasets

### Dataset 2015

In [544]:
df_2015.head()

,Country,Year,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,2015,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,2015,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,2015,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,2015,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,2015,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [546]:
df_2015.shape

(158, 13)

In [548]:
df_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Year                           158 non-null    int64
 2   Region                         158 non-null    object
 3   Happiness Rank                 158 non-null    int64
 4   Happiness Score                158 non-null    float64
 5   Standard Error                 158 non-null    float64
 6   Economy (GDP per Capita)       158 non-null    float64
 7   Family                         158 non-null    float64
 8   Health (Life Expectancy)       158 non-null    float64
 9   Freedom                        158 non-null    float64
 10  Trust (Government Corruption)  158 non-null    float64
 11  Generosity                     158 non-null    float64
 12  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(2), object(2)
memory usage: 16.2+ KB

### Dataset 2016

In [551]:
df_2016.head()

,Country,Year,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,2016,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,2016,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,2016,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,2016,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,2016,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [553]:
df_2016.shape

(157, 14)

In [555]:
df_2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        157 non-null    object
 1   Year                           157 non-null    int64
 2   Region                         157 non-null    object
 3   Happiness Rank                 157 non-null    int64
 4   Happiness Score                157 non-null    float64
 5   Lower Confidence Interval      157 non-null    float64
 6   Upper Confidence Interval      157 non-null    float64
 7   Economy (GDP per Capita)       157 non-null    float64
 8   Family                         157 non-null    float64
 9   Health (Life Expectancy)       157 non-null    float64
 10  Freedom                        157 non-null    float64
 11  Trust (Government Corruption)  157 non-null    float64
 12  Generosity                     157 non-null    float64
 13  Dystopia Residual              157 non-null    float64
dtypes: float64(10), int64(2), object(2)
memory usage: 17.3+ KB

### Dataset 2017

In [560]:
df_2017.head()

,Country,Year,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,2017,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2017,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,2017,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,2017,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,2017,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [562]:
df_2017.shape

(155, 13)

In [564]:
df_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        155 non-null    object
 1   Year                           155 non-null    int64
 2   Happiness.Rank                 155 non-null    int64
 3   Happiness.Score                155 non-null    float64
 4   Whisker.high                   155 non-null    float64
 5   Whisker.low                    155 non-null    float64
 6   Economy..GDP.per.Capita.       155 non-null    float64
 7   Family                         155 non-null    float64
 8   Health..Life.Expectancy.       155 non-null    float64
 9   Freedom                        155 non-null    float64
 10  Generosity                     155 non-null    float64
 11  Trust..Government.Corruption.  155 non-null    float64
 12  Dystopia.Residual              155 non-null    float64
dtypes: float64(10), int64(2), object(1)
memory usage: 15.9+ KB

### Dataset 2018

In [567]:
df_2018.head()

,Overall rank,Country or region,Year,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,2018,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,2018,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,2018,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,2018,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,2018,7.487,1.420,1.549,0.927,0.660,0.256,0.357

In [569]:
df_2018.shape

(156, 10)

In [571]:
df_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Year                          156 non-null    int64
 3   Score                         156 non-null    float64
 4   GDP per capita                156 non-null    float64
 5   Social support                156 non-null    float64
 6   Healthy life expectancy       156 non-null    float64
 7   Freedom to make life choices  156 non-null    float64
 8   Generosity                    156 non-null    float64
 9   Perceptions of corruption     155 non-null    float64
dtypes: float64(7), int64(2), object(1)
memory usage: 12.3+ KB

### Dataset 2019

In [574]:
df_2019.head()

,Overall rank,Country or region,Year,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,2019,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,2019,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,2019,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,2019,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,2019,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [576]:
df_2018.shape

(156, 10)

In [578]:
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Year                          156 non-null    int64
 3   Score                         156 non-null    float64
 4   GDP per capita                156 non-null    float64
 5   Social support                156 non-null    float64
 6   Healthy life expectancy       156 non-null    float64
 7   Freedom to make life choices  156 non-null    float64
 8   Generosity                    156 non-null    float64
 9   Perceptions of corruption     156 non-null    float64
dtypes: float64(7), int64(2), object(1)
memory usage: 12.3+ KB

## Renaming column in each dataset

In [581]:
# Renaming column in the dataset 2017

df_2017.rename (columns = {'Country' : 'Country',
                            'Happiness.Rank' : 'Happiness Rank', 
                           'Happiness.Score' : 'Happiness Score',
                           'Economy..GDP.per.Capita.' : 'Economy (GDP per Capita)',
                           'Health..Life.Expectancy.' : 'Health (Life Expectancy)',
                           'Trust..Government.Corruption.' : 'Trust (Government Corruption)',
                             }, inplace = True)

In [583]:
# Renaming columns in the dataset 2018

df_2018.rename (columns = {'Country or region' : 'Country',
                            'Overall rank' : 'Happiness Rank', 
                           'Score' : 'Happiness Score',
                           'GDP per capita' : 'Economy (GDP per Capita)',
                           'Healthy life expectancy' : 'Health (Life Expectancy)',
                           'Perceptions of corruption' : 'Trust (Government Corruption)',
                            'Freedom to make life choices' : 'Freedom'
                          }, inplace = True)

In [585]:
# Renaming colums in the dataset 2019
df_2019.rename (columns = {'Country or region' : 'Country',
                            'Overall rank' : 'Happiness Rank', 
                           'Score' : 'Happiness Score',
                           'GDP per capita' : 'Economy (GDP per Capita)',
                           'Healthy life expectancy' : 'Health (Life Expectancy)',
                           'Perceptions of corruption' : 'Trust (Government Corruption)',
                            'Freedom to make life choices' : 'Freedom'
                          }, inplace = True)

In [587]:
# Checking the changes
df_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        155 non-null    object
 1   Year                           155 non-null    int64
 2   Happiness Rank                 155 non-null    int64
 3   Happiness Score                155 non-null    float64
 4   Whisker.high                   155 non-null    float64
 5   Whisker.low                    155 non-null    float64
 6   Economy (GDP per Capita)       155 non-null    float64
 7   Family                         155 non-null    float64
 8   Health (Life Expectancy)       155 non-null    float64
 9   Freedom                        155 non-null    float64
 10  Generosity                     155 non-null    float64
 11  Trust (Government Corruption)  155 non-null    float64
 12  Dystopia.Residual              155 non-null    float64
dtypes: float64(10), int64(2), object(1)
memory usage: 15.9+ KB

In [589]:
df_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Happiness Rank                 156 non-null    int64
 1   Country                        156 non-null    object
 2   Year                           156 non-null    int64
 3   Happiness Score                156 non-null    float64
 4   Economy (GDP per Capita)       156 non-null    float64
 5   Social support                 156 non-null    float64
 6   Health (Life Expectancy)       156 non-null    float64
 7   Freedom                        156 non-null    float64
 8   Generosity                     156 non-null    float64
 9   Trust (Government Corruption)  155 non-null    float64
dtypes: float64(7), int64(2), object(1)
memory usage: 12.3+ KB

In [591]:
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Happiness Rank                 156 non-null    int64
 1   Country                        156 non-null    object
 2   Year                           156 non-null    int64
 3   Happiness Score                156 non-null    float64
 4   Economy (GDP per Capita)       156 non-null    float64
 5   Social support                 156 non-null    float64
 6   Health (Life Expectancy)       156 non-null    float64
 7   Freedom                        156 non-null    float64
 8   Generosity                     156 non-null    float64
 9   Trust (Government Corruption)  156 non-null    float64
dtypes: float64(7), int64(2), object(1)
memory usage: 12.3+ KB

## Changing datatypes for years, happiness rank in each dataset

In [594]:
df_2015[['Year', 'Happiness Rank']] = df_2015[['Year', 'Happiness Rank']].astype(str)
df_2016[['Year', 'Happiness Rank']] = df_2016[['Year', 'Happiness Rank']].astype(str)
df_2017[['Year', 'Happiness Rank']] = df_2017[['Year', 'Happiness Rank']].astype(str)
df_2018[['Year', 'Happiness Rank']] = df_2018[['Year', 'Happiness Rank']].astype(str)
df_2019 [['Year', 'Happiness Rank']] = df_2019[['Year', 'Happiness Rank']].astype(str)

In [600]:
df_2015.info() ###checking the changes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Year                           158 non-null    object
 2   Region                         158 non-null    object
 3   Happiness Rank                 158 non-null    object
 4   Happiness Score                158 non-null    float64
 5   Standard Error                 158 non-null    float64
 6   Economy (GDP per Capita)       158 non-null    float64
 7   Family                         158 non-null    float64
 8   Health (Life Expectancy)       158 non-null    float64
 9   Freedom                        158 non-null    float64
 10  Trust (Government Corruption)  158 non-null    float64
 11  Generosity                     158 non-null    float64
 12  Dystopia Residual              158 non-null    float64
dtypes: float64(9), object(4)
memory usage: 16.2+ KB

In [602]:
df_2016.info() ##checking the changes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        157 non-null    object
 1   Year                           157 non-null    object
 2   Region                         157 non-null    object
 3   Happiness Rank                 157 non-null    object
 4   Happiness Score                157 non-null    float64
 5   Lower Confidence Interval      157 non-null    float64
 6   Upper Confidence Interval      157 non-null    float64
 7   Economy (GDP per Capita)       157 non-null    float64
 8   Family                         157 non-null    float64
 9   Health (Life Expectancy)       157 non-null    float64
 10  Freedom                        157 non-null    float64
 11  Trust (Government Corruption)  157 non-null    float64
 12  Generosity                     157 non-null    float64
 13  Dystopia Residual              157 non-null    float64
dtypes: float64(10), object(4)
memory usage: 17.3+ KB

## Deleting columns Region for 2015 and 2016

In [605]:
# Deleting region as it does not appear on the other dataset

df_2015.drop(columns=['Region'], inplace=True)
df_2016.drop(columns=['Region'], inplace=True)

## Descriptive analysis

In [608]:
df_2015.describe()

,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,5.375734,0.047885,0.846137,0.991046,0.630259,0.428615,0.143422,0.237296,2.098977
std,1.145010,0.017146,0.403121,0.272369,0.247078,0.150693,0.120034,0.126685,0.553550
min,2.839000,0.018480,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.328580
25%,4.526000,0.037268,0.545808,0.856823,0.439185,0.328330,0.061675,0.150553,1.759410
50%,5.232500,0.043940,0.910245,1.029510,0.696705,0.435515,0.107220,0.216130,2.095415
75%,6.243750,0.052300,1.158448,1.214405,0.811013,0.549092,0.180255,0.309883,2.462415
max,7.587000,0.136930,1.690420,1.402230,1.025250,0.669730,0.551910,0.795880,3.602140

In [610]:
df_2016.describe()

,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000,157.000000
mean,5.382185,5.282395,5.481975,0.953880,0.793621,0.557619,0.370994,0.137624,0.242635,2.325807
std,1.141674,1.148043,1.136493,0.412595,0.266706,0.229349,0.145507,0.111038,0.133756,0.542220
min,2.905000,2.732000,3.078000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.817890
25%,4.404000,4.327000,4.465000,0.670240,0.641840,0.382910,0.257480,0.061260,0.154570,2.031710
50%,5.314000,5.237000,5.419000,1.027800,0.841420,0.596590,0.397470,0.105470,0.222450,2.290740
75%,6.269000,6.154000,6.434000,1.279640,1.021520,0.729930,0.484530,0.175540,0.311850,2.664650
max,7.526000,7.460000,7.669000,1.824270,1.183260,0.952770,0.608480,0.505210,0.819710,3.837720

In [612]:
df_2017.describe()

,Happiness Score,Whisker.high,Whisker.low,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia.Residual
count,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000
mean,5.354019,5.452326,5.255713,0.984718,1.188898,0.551341,0.408786,0.246883,0.123120,1.850238
std,1.131230,1.118542,1.145030,0.420793,0.287263,0.237073,0.149997,0.134780,0.101661,0.500028
min,2.693000,2.864884,2.521116,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.377914
25%,4.505500,4.608172,4.374955,0.663371,1.042635,0.369866,0.303677,0.154106,0.057271,1.591291
50%,5.279000,5.370032,5.193152,1.064578,1.253918,0.606042,0.437454,0.231538,0.089848,1.832910
75%,6.101500,6.194600,6.006527,1.318027,1.414316,0.723008,0.516561,0.323762,0.153296,2.144654
max,7.537000,7.622030,7.479556,1.870766,1.610574,0.949492,0.658249,0.838075,0.464308,3.117485

In [614]:
df_2018.describe()

,Happiness Score,Economy (GDP per Capita),Social support,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption)
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,155.000000
mean,5.375917,0.891449,1.213237,0.597346,0.454506,0.181006,0.112000
std,1.119506,0.391921,0.302372,0.247579,0.162424,0.098471,0.096492
min,2.905000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.453750,0.616250,1.066750,0.422250,0.356000,0.109500,0.051000
50%,5.378000,0.949500,1.255000,0.644000,0.487000,0.174000,0.082000
75%,6.168500,1.197750,1.463000,0.777250,0.578500,0.239000,0.137000
max,7.632000,2.096000,1.644000,1.030000,0.724000,0.598000,0.457000

In [616]:
df_2019.describe()

,Happiness Score,Economy (GDP per Capita),Social support,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption)
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,5.407096,0.905147,1.208814,0.725244,0.392571,0.184846,0.110603
std,1.113120,0.398389,0.299191,0.242124,0.143289,0.095254,0.094538
min,2.853000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.544500,0.602750,1.055750,0.547750,0.308000,0.108750,0.047000
50%,5.379500,0.960000,1.271500,0.789000,0.417000,0.177500,0.085500
75%,6.184500,1.232500,1.452500,0.881750,0.507250,0.248250,0.141250
max,7.769000,1.684000,1.624000,1.141000,0.631000,0.566000,0.453000

## Finding missing values in the datasets

In [619]:
df_2015.isnull().sum()

Country                          0
Year                             0
Happiness Rank                   0
Happiness Score                  0
Standard Error                   0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64

In [621]:
df_2016.isnull().sum()

Country                          0
Year                             0
Happiness Rank                   0
Happiness Score                  0
Lower Confidence Interval        0
Upper Confidence Interval        0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64

In [623]:
df_2017.isnull().sum()

Country                          0
Year                             0
Happiness Rank                   0
Happiness Score                  0
Whisker.high                     0
Whisker.low                      0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Generosity                       0
Trust (Government Corruption)    0
Dystopia.Residual                0
dtype: int64

In [625]:
df_2018.isnull().sum()

Happiness Rank                   0
Country                          0
Year                             0
Happiness Score                  0
Economy (GDP per Capita)         0
Social support                   0
Health (Life Expectancy)         0
Freedom                          0
Generosity                       0
Trust (Government Corruption)    1
dtype: int64

In [627]:
df_2019.isnull().sum()

Happiness Rank                   0
Country                          0
Year                             0
Happiness Score                  0
Economy (GDP per Capita)         0
Social support                   0
Health (Life Expectancy)         0
Freedom                          0
Generosity                       0
Trust (Government Corruption)    0
dtype: int64

In [629]:
df_2018_NaN = df_2018[df_2018['Trust (Government Corruption)'].isnull() == True]

In [631]:
df_2018_NaN

,Happiness Rank,Country,Year,Happiness Score,Economy (GDP per Capita),Social support,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption)
19,20,United Arab Emirates,2018,6.774,2.096,0.776,0.67,0.284,0.186,NaN

## Checking for duplicates

In [634]:
df_2015.duplicated().sum()

0

In [636]:
df_2016.duplicated().sum()

0

In [638]:
df_2017.duplicated().sum()

0

In [640]:
df_2018.duplicated().sum()

0

In [642]:
df_2019.duplicated().sum()

0

In [648]:
df_2017

,Country,Year,Happiness Rank,Happiness Score,Whisker.high,Whisker.low,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia.Residual
0,Norway,2017,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2017,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,2017,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,2017,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,2017,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182
...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,2017,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
151,Syria,2017,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
152,Tanzania,2017,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130
153,Burundi,2017,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
154,Central African Republic,2017,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005

In [650]:
df_2016

,Country,Year,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,2016,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,2016,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,2016,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,2016,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,2016,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596
...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Benin,2016,153,3.484,3.404,3.564,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812
153,Afghanistan,2016,154,3.360,3.288,3.432,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
154,Togo,2016,155,3.303,3.192,3.414,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540
155,Syria,2016,156,3.069,2.936,3.202,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789
156,Burundi,2016,157,2.905,2.732,3.078,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404

## Merging all the datasets based on the country variable

In [668]:
## Since the year 2017 was not appearing on the columns names, I am adding the year suffixes to each column before merging

# Function to add year suffix to column names (excluding 'Country')
def add_year_suffix(df, year):
    df = df.rename(columns=lambda x: f"{x}_{year}" if x != "Country" else x)
    return df

# Add year suffix to columns
df_2015 = add_year_suffix(df_2015, 2015)
df_2016 = add_year_suffix(df_2016, 2016)
df_2017 = add_year_suffix(df_2017, 2017)
df_2018 = add_year_suffix(df_2018, 2018)
df_2019 = add_year_suffix(df_2019, 2019)

In [670]:
# Merge datasets step by step
all_years_merge = df_2015.merge(df_2016, on='Country', suffixes=('_2015', '_2016'))
all_years_merge = all_years_merge.merge(df_2017, on='Country', suffixes=('', '_2017'))
all_years_merge = all_years_merge.merge(df_2018, on='Country', suffixes=('', '_2018'))
all_years_merge = all_years_merge.merge(df_2019, on='Country', suffixes=('', '_2019'))

In [672]:
# Display all the columns
pd.set_option('display.max_columns', None)

In [676]:
all_years_merge

,Country,Year_2015,Happiness Rank_2015,Happiness Score_2015,Standard Error_2015,Economy (GDP per Capita)_2015,Family_2015,Health (Life Expectancy)_2015,Freedom_2015,Trust (Government Corruption)_2015,Generosity_2015,Dystopia Residual_2015,Year_2016,Happiness Rank_2016,Happiness Score_2016,Lower Confidence Interval_2016,Upper Confidence Interval_2016,Economy (GDP per Capita)_2016,Family_2016,Health (Life Expectancy)_2016,Freedom_2016,Trust (Government Corruption)_2016,Generosity_2016,Dystopia Residual_2016,Year_2017,Happiness Rank_2017,Happiness Score_2017,Whisker.high_2017,Whisker.low_2017,Economy (GDP per Capita)_2017,Family_2017,Health (Life Expectancy)_2017,Freedom_2017,Generosity_2017,Trust (Government Corruption)_2017,Dystopia.Residual_2017,Happiness Rank_2018,Year_2018,Happiness Score_2018,Economy (GDP per Capita)_2018,Social support_2018,Health (Life Expectancy)_2018,Freedom_2018,Generosity_2018,Trust (Government Corruption)_2018,Happiness Rank_2019,Year_2019,Happiness Score_2019,Economy (GDP per Capita)_2019,Social support_2019,Health (Life Expectancy)_2019,Freedom_2019,Generosity_2019,Trust (Government Corruption)_2019
0,Switzerland,2015,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2016,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463,2017,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716,5,2018,7.487,1.420,1.549,0.927,0.660,0.256,0.357,6,2019,7.480,1.452,1.526,1.052,0.572,0.263,0.343
1,Iceland,2015,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2016,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137,2017,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715,4,2018,7.495,1.343,1.644,0.914,0.677,0.353,0.138,4,2019,7.494,1.380,1.624,1.026,0.591,0.354,0.118
2,Denmark,2015,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2016,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939,2017,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707,3,2018,7.555,1.351,1.590,0.868,0.683,0.284,0.408,2,2019,7.600,1.383,1.573,0.996,0.592,0.252,0.410
3,Norway,2015,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2016,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465,2017,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027,2,2018,7.594,1.456,1.582,0.861,0.686,0.286,0.340,3,2019,7.554,1.488,1.582,1.028,0.603,0.271,0.341
4,Canada,2015,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2016,6,7.404,7.335,7.473,1.44015,1.09610,0.82760,0.57370,0.31329,0.44834,2.70485,2017,7,7.316,7.384403,7.247597,1.479204,1.481349,0.834558,0.611101,0.435540,0.287372,2.187264,7,2018,7.328,1.330,1.532,0.896,0.653,0.321,0.291,9,2019,7.278,1.365,1.505,1.039,0.584,0.285,0.308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Rwanda,2015,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042,2016,152,3.515,3.444,3.586,0.32846,0.61586,0.31865,0.54320,0.50521,0.23552,0.96819,2017,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061,151,2018,3.408,0.332,0.896,0.400,0.636,0.200,0.444,152,2019,3.334,0.359,0.711,0.614,0.555,0.217,0.411
137,Benin,2015,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328,2016,153,3.484,3.404,3.564,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812,2017,143,3.657,3.745784,3.568217,0.431085,0.435300,0.209930,0.425963,0.207948,0.060929,1.885631,136,2018,4.141,0.378,0.372,0.240,0.440,0.163,0.067,102,2019,4.883,0.393,0.437,0.397,0.349,0.175,0.082
138,Syria,2015,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858,2016,156,3.069,2.936,3.202,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789,2017,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574,150,2018,3.462,0.689,0.382,0.539,0.088,0.376,0.144,149,2019,3.462,0.619,0.378,0.440,0.013,0.331,0.141
139,Burundi,2015,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302,2016,157,2.905,2.732,3.078,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404,2017,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024,156,2018,2.905,0.091,0.627,0.145,0.065,0.149,0.076,145,2019,3.775,0.046,0.447,0.380,0.220,0.176,0.180
140,Togo,2015,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726,2016,155,3.303,3.192,3.414,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540,2017,150,3.495,3.594038,3.395962,0.305445,0.431883,0.247106,0.380426,0.196896,0.095665,1.837229,139,2018,3.999,0.259,0.474,0.253,0.434,0.158,0.101,139,2019,4.085,0.275,0.572,0.410,0.293,0.177,0.085

In [678]:
# Deleting the years columns
columns_to_drop = [col for col in all_years_merge.columns if 'Year' in col]
all_years_merge = all_years_merge.drop(columns=columns_to_drop)

In [680]:
all_years_merge

,Country,Happiness Rank_2015,Happiness Score_2015,Standard Error_2015,Economy (GDP per Capita)_2015,Family_2015,Health (Life Expectancy)_2015,Freedom_2015,Trust (Government Corruption)_2015,Generosity_2015,Dystopia Residual_2015,Happiness Rank_2016,Happiness Score_2016,Lower Confidence Interval_2016,Upper Confidence Interval_2016,Economy (GDP per Capita)_2016,Family_2016,Health (Life Expectancy)_2016,Freedom_2016,Trust (Government Corruption)_2016,Generosity_2016,Dystopia Residual_2016,Happiness Rank_2017,Happiness Score_2017,Whisker.high_2017,Whisker.low_2017,Economy (GDP per Capita)_2017,Family_2017,Health (Life Expectancy)_2017,Freedom_2017,Generosity_2017,Trust (Government Corruption)_2017,Dystopia.Residual_2017,Happiness Rank_2018,Happiness Score_2018,Economy (GDP per Capita)_2018,Social support_2018,Health (Life Expectancy)_2018,Freedom_2018,Generosity_2018,Trust (Government Corruption)_2018,Happiness Rank_2019,Happiness Score_2019,Economy (GDP per Capita)_2019,Social support_2019,Health (Life Expectancy)_2019,Freedom_2019,Generosity_2019,Trust (Government Corruption)_2019
0,Switzerland,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716,5,7.487,1.420,1.549,0.927,0.660,0.256,0.357,6,7.480,1.452,1.526,1.052,0.572,0.263,0.343
1,Iceland,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715,4,7.495,1.343,1.644,0.914,0.677,0.353,0.138,4,7.494,1.380,1.624,1.026,0.591,0.354,0.118
2,Denmark,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707,3,7.555,1.351,1.590,0.868,0.683,0.284,0.408,2,7.600,1.383,1.573,0.996,0.592,0.252,0.410
3,Norway,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027,2,7.594,1.456,1.582,0.861,0.686,0.286,0.340,3,7.554,1.488,1.582,1.028,0.603,0.271,0.341
4,Canada,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,6,7.404,7.335,7.473,1.44015,1.09610,0.82760,0.57370,0.31329,0.44834,2.70485,7,7.316,7.384403,7.247597,1.479204,1.481349,0.834558,0.611101,0.435540,0.287372,2.187264,7,7.328,1.330,1.532,0.896,0.653,0.321,0.291,9,7.278,1.365,1.505,1.039,0.584,0.285,0.308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Rwanda,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042,152,3.515,3.444,3.586,0.32846,0.61586,0.31865,0.54320,0.50521,0.23552,0.96819,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061,151,3.408,0.332,0.896,0.400,0.636,0.200,0.444,152,3.334,0.359,0.711,0.614,0.555,0.217,0.411
137,Benin,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328,153,3.484,3.404,3.564,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812,143,3.657,3.745784,3.568217,0.431085,0.435300,0.209930,0.425963,0.207948,0.060929,1.885631,136,4.141,0.378,0.372,0.240,0.440,0.163,0.067,102,4.883,0.393,0.437,0.397,0.349,0.175,0.082
138,Syria,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858,156,3.069,2.936,3.202,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574,150,3.462,0.689,0.382,0.539,0.088,0.376,0.144,149,3.462,0.619,0.378,0.440,0.013,0.331,0.141
139,Burundi,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302,157,2.905,2.732,3.078,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024,156,2.905,0.091,0.627,0.145,0.065,0.149,0.076,145,3.775,0.046,0.447,0.380,0.220,0.176,0.180
140,Togo,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726,155,3.303,3.192,3.414,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540,150,3.495,3.594038,3.395962,0.305445,0.431883,0.247106,0.380426,0.196896,0.095665,1.837229,139,3.999,0.259,0.474,0.253,0.434,0.158,0.101,139,4.085,0.275,0.572,0.410,0.293,0.177,0.085

## Exporting the merged datasets

In [688]:
all_years_merge.to_csv(os.path.join(path, 'Data sets', 'Prepared Data Happiness', 'all_years_merge.csv'))

In [690]:
os.getcwd()

'C:\\Users\\salmi'